flags = {
    "Inglaterra": "🏴",
    "Francia": "🇫🇷",
    "Alemania": "🇩🇪",
    "España": "🇪🇸",
    "Portugal": "🇵🇹",
    "Países Bajos": "🇳🇱",
    "Bélgica": "🇧🇪",
    "Suiza": "🇨🇭",
    "Austria": "🇦🇹",
    "Suecia": "🇸🇪",
    "República Checa": "🇨🇿",
    "Bosnia y Herzegovina": "🇧🇦",
    "Turquía": "🇹🇷",
    "Escocia": "🏴",
    "Noruega": "🇳🇴",
    "Dinamarca": "🇩🇰",

    "Argentina": "🇦🇷",
    "Brasil": "🇧🇷",
    "Uruguay": "🇺🇾",
    "Colombia": "🇨🇴",
    "Ecuador": "🇪🇨",
    "Paraguay": "🇵🇾",

    "Estados Unidos": "🇺🇸",
    "México": "🇲🇽",
    "Canadá": "🇨🇦",
    "Panamá": "🇵🇦",
    "Curazao": "🇨🇼",
    "Haití": "🇭🇹",

    "Marruecos": "🇲🇦",
    "Egipto": "🇪🇬",
    "Senegal": "🇸🇳",
    "Costa de Marfil": "🇨🇮",
    "Argelia": "🇩🇿",
    "Túnez": "🇹🇳",
    "Ghana": "🇬🇭",
    "Sudáfrica": "🇿🇦",
    "Cabo Verde": "🇨🇻",
    "República Democrática del Congo": "🇨🇩",

    "Japón": "🇯🇵",
    "Corea del Sur": "🇰🇷",
    "Irán": "🇮🇷",
    "Australia": "🇦🇺",
    "Arabia Saudita": "🇸🇦",
    "Qatar": "🇶🇦",
    "Uzbekistán": "🇺🇿",
    "Jordania": "🇯🇴",
    "Iraq": "🇮🇶",
    "Nueva Zelanda": "🇳🇿",

    "Especiales": "🏳️",
    "FW": "🏳️"
}